### ISSUE TITLE
Date search is unpredictable with dates before 1000

### ISSUE THREAD

**Issue by jhallida** [projectblacklight/arclight#1017]
It looks like dates before the year 1000 will cause unpredictable and incorrect behavior when using the date slider search functionality in ArcLight. Core problem seems to be that blacklight_range_limit wants an integer but the date field is a string.

**Comment by dinahhandel** [comment]
Does blacklight_range_limit work with Blacklight 8? Gem spec allows Blacklight 8, but needs more investigation.

**Comment by jcoyne** [comment]
Blacklight-range-limit is no longer part of arclight. Should we close this issue or move it to the blacklight-range-limit repo?

**Comment by seanaery** [comment]
Good question, @jcoyne. Since `blacklight_range_limit`'s docs clearly indicate it is for integer fields only, I think the ticket is OK living here in arclight rather than moving it. I just did some local testing on our local ArcLight app and capturing the date range as `_isim` instead of `_ssim` does fix issues for us when we have date values < 1000 (we use a modified version of `blacklight_range_limit` without the JS). Can't see any downsides to switching this field over from a string to integer. I'll go ahead and take the ticket.
