### ISSUE TITLE
Search bar display on smaller viewports looks bad

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/arclight#1239]
![Screen Shot 2022-10-27 at 10 09 39](https://user-images.githubusercontent.com/111218/198354922-8782c1c7-3c2e-49f1-ae11-7c3157d48694.png)

**Comment by ggeisler** [comment]
I think at at `md` and wider breakpoints we're okay:

<img width="766" alt="Screen Shot 2022-10-31 at 11 28 52 AM" src="https://user-images.githubusercontent.com/101482/199083083-cf9e76ad-47a1-4483-a998-3b836b8bf327.png">

---

At below `md`, I suggest we put the two distinct groups of elements on their own line:

<img width="574" alt="Screen Shot 2022-10-31 at 11 25 17 AM" src="https://user-images.githubusercontent.com/101482/199083253-30ba2863-4992-48cb-b7cb-9e483ce18bc4.png">

My rough, possibly incorrect, reading of the relevant code is that we should be putting the new, ArcLight-specfic elements (the "Search" and "this collection | all collections" elements) in their own input-group instead of just inserting them into Blacklight's existing input-group. And then we display both input-groups on a single line at `md` and above, but on their own line at below `md`.

Also, to better handle the really narrow viewports, maybe we should drop the "Search" text part of the button label at below `sm` viewport (or even at below `md` just to keep things simple, although with the two button groups in their own row I don't think the text label is a problem until we get into the `xs` viewport range):


<img width="503" alt="Screen Shot 2022-10-31 at 11 45 12 AM" src="https://user-images.githubusercontent.com/101482/199085595-dca2b104-7eb5-4aaa-aa71-cd4ac79076ca.png">

Note that in the mockup above I also increased the size of the search icon. It looks like it is currently set to be `1rem` and we really should make it more like `24px` (or `1.5rem`).

**Comment by marlo-longley** [comment]
Blocked by Blacklight PRs?
Team should pair on this.
