### ISSUE TITLE
Contain autocomplete dropdown within viewport

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#1383]
This occurs in Firefox, Chrome, and Safari so doesn't seem to be a browser issue:

<img width="1204" alt="Screen Shot 2023-01-10 at 3 39 09 PM" src="https://user-images.githubusercontent.com/101482/211677680-7480a6b7-ea73-412e-9fd2-e6d9285a4dbf.png">

---

It appears to be a responsive issue, in that it fits at `1160px` and wider, but doesn't adjust at viewport widths below `1160px`.

**Comment by lfarrell** [comment]
The bug is present at screen sizes larger than `1160px`. The screenshot below is from a screen at `1600px`. Instead it seems to be the length of the suggested title. The underlying problem is that titles aren't allowed to wrap.


![Image](https://github.com/projectblacklight/arclight/assets/436691/3b8d6a6e-12f8-4c45-88c4-269aa34af0f8)

**Comment by lfarrell** [comment]
PR to fix this issue: https://github.com/projectblacklight/arclight/pull/1428

**Comment by marlo-longley** [comment]
Closed via #1428
