### ISSUE TITLE
Investigate Advanced search

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#248]
**Acceptance criteria**

* Provide documentation about how to install/configure the Blacklight Advanced Search plugin
* For the demo site, include a configured advanced search setup, including "all fields", "names", "subjects", "places," and "titles"

**Comment by mejackreed** [comment]
Will require some updates to the upstream plugin

**Comment by anarchivist** [comment]
First round of work:

* Estimate the level of effort necessary to update the upstream plugin

**Comment by drh-stanford** [comment]
Talked to @mejackreed about this ticket. I will look into what changes are needed to the plugin for compatibility with Blacklight `master`, and what configuration changes would be needed for ArcLight.

An example of the plugin in use is SearchWorks -- https://searchworks.stanford.edu/advanced

**Comment by drh-stanford** [comment]
Here's a list of problems that I found that we'd need to fix -- the first 2 I've done locally but the rest I haven't tried:

1. blacklight needs a PR to fix the `label_for_search_field` method
1. blacklight_advanced_search needs PRs to fix:
   1. replacing `search_field_def_for_key` with `blacklight_config.search_fields[key]`
   1. replacing `solr_field` with `field_name` in the view for facet limits
   1. using `Blacklight::SearchService.new(blacklight_config, params)` for the search service in the advanced controller
1. PRs to make blacklight_range_limit work with blacklight_advanced_search. I had to remove the range limit plugin to get the advanced search to work
1. Alter the configuration so we have only the fields we want in the advanced search UI
1. testing the various combinations for the Advanced search UI -- I only did a few
1. any UI customization that we want to do -- I didn't see a mockup for the advanced search screen

### Default advanced search screen

![screen shot 2017-05-31 at 12 06 41 pm](https://cloud.githubusercontent.com/assets/1861171/26649647/8c57d512-45fb-11e7-8fb8-37ab09f70b33.png)

**Comment by drh-stanford** [comment]
- [ ] Add documentation on the Wiki for those interested in this adv search

**Comment by seanaery** [comment]
Blacklight 8 has a built-in native Advanced Search, so this is kind of already done: https://arclight-demo.projectblacklight.org/catalog/advanced. Adding some documentation and/or a link in the ArcLight UI to get to it would be a reasonably small task.

**Comment by seanaery** [comment]
Turns out adding Advanced Search to ArcLight (or any other Blacklight application) is not _yet_ straightforward. There is a bug in Solr affecting versions 7.3 and up that prevents the built-in features from working without implementing some workarounds, per:
https://github.com/projectblacklight/blacklight/wiki/Advanced-Search#configuration

As for this "investigate" ticket, perhaps we can treat this as done. Depending on how the team would like to proceed, we could potentially spawn a couple followup tickets, i.e.:
- Make `config.advanced_search.enabled = true` actually render an `Advanced` link in the ArcLight UI
- Create wiki documentation about how to [implement the workaround](https://github.com/projectblacklight/blacklight/wiki/Advanced-Search#configuration) to make the form work correctly

**Comment by seanaery** [comment]
Closing this issue as it has been investigated.
