### ISSUE TITLE
Address usability of very long contents lists

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#534]
Navigating across series, etc. in long contents lists can be really challenging. Impacts navigation often on collection-level records. 

Feedback from estimation:

* IU - would like to increase the hierarchy of table of contents to the container level to give users a better sense of orientation, especially for larger finding aids.
* DUKE: would preferably address via a new feature (Persistent hierarchical component navigation).

**Comment by ggeisler** [comment]
I believe the Duke and IU comments are about two different things.

Duke: 
> In Arclight, there is no straightforward (or default) way to view or navigate a collection in its entirety.

The "Contents" tab available at the collection level does provide a way to view and navigate the collection in its entirety, doesn't it?

> Staff unanimously preferred the ASpace PUI’s navigable file-tree representation of a collection to ArcLight’s hierarchical context indicators, and liked how this was visible instantly from the PUI collection landing page.

This second comment makes it seem that what Duke really is asking for is an always visible collection navigation tree. For reference, here's how ASpace's persistent collection navigation tree looks:

![Screen Shot 2019-07-23 at 9 59 54 AM](https://user-images.githubusercontent.com/101482/61733827-7dfb3d80-ad35-11e9-9810-d7c8bbc1ffe2.png)


IU:
> Increase the hierarchy of table of contents to the container level to give users a better sense of orientation, especially for larger finding aids

Because of the reference to "increase the hierarchy of table of contents," I think this comment refers to the component detail page context, and they are asking for the display of more extensive context surrounding the current component. I've created a new issue to consider that specifically: #547.

Perhaps then this ticket should focus on if and how we could display a persistent collection navigation tree? Possible related ticket with discussion is #336.

**Comment by anarchivist** [comment]
From 20190724 call:

* IU: If there are plans to make changes to provide better context, we are very interested in seeing that. What we have at IU isn't fully fleshed out, but we provide the second component level as a side table of contents
* We should also look at this in the context of cleaning up the page layout, and determine whether a full tree view (#546) is useful.
* Duke: This issue was probably the biggest ask - feedback was that they wanted something like ArcLight but with the ASpace PUI's persistent tree navigation.

**Comment by anarchivist** [comment]
Ref #668

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. In v1 there's a persistent hierarchy tree navigator and paginated child component nav on a component show page.
