### ISSUE TITLE
Document needed information for a generic request application

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#561]
For a generic/custom request application, document what is the bare minimum needed information for generation of a request.

The acceptance criteria for this ticket is the following:
 - [ ] determine a request that may be made from ArcLight for a given item from your (or another) organization. For help with this ask your institutional PO or @anarchivist 
 - [ ] document what information is needed for this request

**Comment by seanaery** [comment]
Count Duke among the institutions needing to accommodate a generic/custom request application. While we do use Aeon (hosted / v4.1.0), we don't currently have or need to support direct finding aids to Aeon integration/interaction, so we're less concerned with #560 . We have an intermediary locally-developed Requests app in between, and the connection happens only at the collection level. Happy to provide more documentation / ideation as needed.

**Comment by eckardm** [comment]
In case this is helpful, our current request workflow is based on our finding aid platform (DLXS) knowing the ArchivesSpace 'ref_id' for a given component. When someone makes a request, then, I could see this as being the absolute bare minimum needed, and any additional information needed for a request management system could be pulled from there. Of course, that presumes that you have a system for descriptive and administrative information like ArchivesSpace in place, and that you use the Resources and Locations modules, and, at least in our case, that ArchivesSpace is customized so that descriptive and administrative metadata is available at a single endpoint (see @djpillen [BHL Barcode](https://github.com/bentley-historical-library/bhl_barcode) plug-in, and Dallas feel free to correct any of this). That seems like a lot of assumptions.

Short of that, you could just pull that ArchivesSpace ID or other ID and some additional basic info, as we currently do from DLXS:
- Collection title
- Collection ID or call number
- Component title/display title
- Container information, e.g. box number (assuming there's some separate system for tracking the location of that container)

Alternatively, a request could just point/link to the component in ArcLight or ArchivesSpace.

**Comment by jlhardes** [comment]
IU only needs feature parity with what we do now - send a URL referencing the EAD XML for a finding aid to our request service. So each finding aid offers a "Request" link. The "Request" link on [this example finding aid](http://purl.dlib.indiana.edu/iudl/findingaids/lilly/InU-Li-VAA9510) shows the link construction along these lines: 

[serviceURL]?[parameter]=http://purl.dlib.indiana.edu/iudl/findingaids/lilly/encodedtext/InU-Li-VAA9510

Everything for a request happens on Aeon's side for us so our only requirement for integration with ArcLight is constructing that link.
