### ISSUE TITLE
Add component context/actions box to component show page

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#631]
Part of #628.

A new element of the updated component heading area is a box that tells the user which collection the current component is part of and, when available, the name of the container the current component is in. This box also includes global actions that apply to the current component, which includes the bookmark action, and can include a request button and download links. The download links are kind of special and I'll write up those in a separate ticket; they shouldn't affect the basic design of the context/actions box.

## Box placement

- [x] Right-align the box with the right-side of the page content area. 

- [x] Top-align the box with the top of the breadcrumb structure

Something like this:

<img width="1143" alt="Screen Shot 2019-08-26 at 11 55 52 AM" src="https://user-images.githubusercontent.com/101482/63716048-f43e0480-c7f9-11e9-972b-a9ff32cd62c2.png">

## Box contents

There are four potential elements that go in the box:

- Collection ID
- Request button
- Bookmark checkbox
- Current container label

The last one, current container label, is not applicable if the current component page is at the collection level (example A in screenshot below), and it might not always be available at other levels (in which case the box will look like example A even it is at a level below collection). But when we do have the container information, we want to show it in the context box.

<img width="1027" alt="Screen Shot 2019-08-26 at 12 11 09 PM" src="https://user-images.githubusercontent.com/101482/63716540-1be19c80-c7fb-11e9-9773-4c2ca4dfd60a.png">

---

## Box layout

- [x] For the box styling, use (at least for now) the background and border colors currently used for the header of the Page title and  Collection context boxes (see the `al-show-header-section` and `al-document-title-bar` classes):

<img width="844" alt="Screen Shot 2019-08-26 at 12 31 01 PM" src="https://user-images.githubusercontent.com/101482/63717623-88f63180-c7fd-11e9-9899-8a4085d13a73.png">

- [x] Collection ID: use the font styling used in the same examples mentioned above. Left-align in the box.

- [x] If we have a container label to display, add a `|` (vertical bar) followed by a space and then the value of the container label. There shouldn't be a vertical bar if there is no container label to display (as in A in the screenshot).

- [x] Add a request button using `btn btn-secondary btn-sm` styling. Button should be left-aligned with the Collection ID label above it.

- [x] Add the Bookmark checkbox following the request button and some spacing.

- [ ] The width of the box should be variable in that it should only be wide enough to accommodate the elements above and appropriate side margins. So the width of the box will differ depending on whether a given component has a container label to display and how long that label is (e.g., B versus D in the screenshot above).

**Comment by ggeisler** [comment]
From a comment @gordonleacock made during his demo this morning, it sounds like the actions box was **not** added to the collection show page. If it wasn't, note that it **should** be on the collection show page just as it is for lower-level components. 

For an example, see the very first screenshot in the original description of this ticket above (the Vincent Schaefer papers is a collection) or this XD mockup: https://xd.adobe.com/view/22a0aaf2-f3ff-45d1-6fb3-b687b337f02c-5491/screen/b8fc302f-ebb9-4bf7-be54-225a4d291d04/Collection-level-Contents

**Comment by camillevilla** [comment]
Assigned this to myself to indicate I'm working on verifying @ggeisler's comment above.

**Comment by camillevilla** [comment]
- Confirmed: the context / actions box isn't rendered on collection show pages. (🎟)
- One of the issues @gordonleacock mentioned in #695 about collection IDs being unavailable at the component level should be resolved by #750. I'm going to ticket this separately so that it doesn't get lost in the flow. (🎟)
- re: >width of the box should be variable 
I think we need to revisit this as part of #637, or as a follow up task to iron out things with flexbox afterwards.  (🎟)

Fixtures for each of the box content examples:
A: will ticket this explicitly (see above)
B: TBD
C: TBD
D: http://localhost:3000/catalog/ncaids544-testd0e526
![Screen Shot 2019-09-17 at 4 59 54 PM](https://user-images.githubusercontent.com/5402927/65087997-9c179f80-d96c-11e9-8e59-cfd132cfc0d3.png)

**Comment by jvine** [comment]
I don't see this detail mentioned; if I missed it, apologies for duplicating. The height of the box should match its own content, rather the height of the breadcrumb + title on the left.

E.g. this:
<img width="976" alt="Screen Shot 2019-09-17 at 5 46 46 PM" src="https://user-images.githubusercontent.com/6945691/65094764-25ca6b80-d973-11e9-97e4-395c5429debe.png">

rather than this:
<img width="950" alt="Screen Shot 2019-09-17 at 5 43 07 PM" src="https://user-images.githubusercontent.com/6945691/65094660-bd7b8a00-d972-11e9-9bfc-8296d7945ee4.png">

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The component show page has evolved in a different direction enough that the specifics in this ticket are no longer relevant.
