### ISSUE TITLE
Extent "inheriting" children?

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#686]
Just came across these collections that seem to be including every component's extent in the main extent statement. Is that... intentional?

https://arclight-demo.projectblacklight.org/catalog/heschelabraham
https://arclight-demo.projectblacklight.org/catalog/rushbenjaminandjulia
https://arclight-demo.projectblacklight.org/catalog/brownfrankclyde
https://arclight-demo.projectblacklight.org/catalog/ahstephens

**Comment by mejackreed** [comment]
Likely not intentional, but probably an indexing bug. Is the expected behavior to only have that level's extent?

**Comment by jvine** [comment]
> Is the expected behavior to only have that level's extent?

Yes.

**Comment by anarchivist** [comment]
Confirming @jvine's observation here.

**Comment by fordmadox** [comment]
Just took a quick look, and I'd suggest never starting off any of the XPath expressions with "//" unless necessary.  At the start of an expression, // is shorthand for "start at the _document root_ element," hence all descendants of the entire EAD document that match the remaining expression.  Two relevant examples from the XPath spec:
- //para selects all the para descendants of the document root and thus selects all para elements in the same document as the context node
- .//para selects the para element descendants of the context node

The latter is what you'd want, but even that level of greediness could be avoided in most of the expressions (especially the extent statements).  Also, if you can use child rather than descendant expressions, I expect that you'll dramatically speed up processing of large EAD files.  Even something as simple as https://github.com/projectblacklight/arclight/blob/master/lib/arclight/traject/ead2_config.rb#L69, could be changed to something like "/ead/eadheader/eadid"  (also, just curious: is that gsub on the EADID there to handle solr tokenization, repurposing the eadid in a URL, or something else?)

Noah Huffman would be a great person to pair with to go over all of the EAD Xpaths, I bet :)  Also, if EAD3 indexing is ever done, I'd be happy to help out with that.  A lot of the EAD2002 indexed could be reused, and there'd just need to be a few changes/extensions with the control section, dates, and extents.

**Comment by seanaery** [comment]
I agree with @fordmadox on avoiding `//` xpaths in cases where the targeted elements are located in a standard and predictable part of the document tree. It could make a significant difference in indexing speed especially for our biggest finding aids, which approach 10MB of raw XML. I'd expect we'll be able to fine-tune cases like this in a future revision.
CC: @noahgh221
