### ISSUE TITLE
Update list view of search results - D - Bookmark checkbox

### ISSUE THREAD

**Issue by mejackreed** [projectblacklight/arclight#710]
Split out of #669 

<img width="877" alt="Screen Shot 2019-08-28 at 4 36 48 PM" src="https://user-images.githubusercontent.com/101482/63900031-11b6ce00-c9b4-11e9-8809-6c47cee4f009.png">

**D: Bookmark checkbox** - We currently show a bookmark checkbox for each result item. All items should continue to have a bookmark checkbox. What's changed:

- [x] Move the bookmark checkbox so it is right-aligned at the edge of the content area, on the same line as the result item label.
- [x] Replace the text "Bookmark" with a ribbon icon.

**Comment by labradford** [comment]
@ggeisler I have a few questions re: the update to bookmarks
Currently the bookmark checkbox has three different texts associated with it. When the bookmark is not checked it is "Bookmark". When you check the box, it updates to "Saving..." and when it is checked it updates to "In Bookmarks". 
1. Do you want all three of the status to be changed to the bookmark icon?
2. Do you want this change to occur for all instances of the bookmark checkbox? Or just on the search results index? (at first pass, it looks like it also appears on the contents tab on the show pages)

**Comment by ggeisler** [comment]
@labradford 

1. I think we want to use the icon for both the on and off states. For the "Saving.." state, I think maintaining that message would be good, although without seeing it in action I'm not sure if that will cause any issues with horizontal space. But given that is only a message displayed briefly, I think it is worth trying to keep it.

2. The goal is to replace the "Bookmark" label with the icon in places where we are trying to keep things really compact. That applies to the search results and the contents tab for sure. But in other places, such as the component context/actions box at the top of the component show page, I think we want to maintain the default label, since there is room for it. So, no, I don't think we want to globally replace the "Bookmark" label with the icon, though we do want to do it in at least a couple of places.

**Comment by labradford** [comment]
@mejackreed This issue requires a change upstream from Blacklight. https://github.com/projectblacklight/blacklight/pull/2131
Should we pin Arclight to master until this change is updated?

**Comment by mejackreed** [comment]
Sure we can do that
