### ISSUE TITLE
Format chronlist element set for display

### ISSUE THREAD

**Issue by noahgh221** [projectblacklight/arclight#760]
As of 9/11, the Demo application is not applying any formatting to the  `<chronlist>` element set that may appear as a child of a note field (most commonly `<bioghist>`, etc.). The `<chronlist>` element set is typically used to format biographical timelines.

The demo app is displaying the text of the elements as one text block, but not supplying any special formatting (e.g. bullets, newlines, etc.).

Example (see Biographical/Historical section): https://arclight-demo.projectblacklight.org/catalog/rushbenjaminandjulia

Current display:
![image](https://user-images.githubusercontent.com/7328518/64719983-661f7a80-d497-11e9-9e8d-887259d83f46.png)

EAD2002 Tag Library documentation on `<chronlist>` element: http://www.loc.gov/ead/tglib/elements/chronlist.html

For reference, here is how we (Duke) currently display `<chronlist>` elements within `<bioghist>`  for the collection referenced above: https://library.duke.edu/rubenstein/findingaids/rushbenjaminandjulia/#historicalnote

![image](https://user-images.githubusercontent.com/7328518/64720032-83544900-d497-11e9-80be-9ddc760f212b.png)

CC @seanaery

**Comment by ggeisler** [comment]
Below is a recommendation for how to deal with the `<chronlist>` element. As @noahgh221 says above, we don't currently do anything with this element but it should be fairly straightforward to work with it, since there are only a few child elements of `<chronlist>`. Thanks to @noahgh221 for the relevant pointers.

### How a chronlist should look
Here's the target for displaying the chronlist (note there are two separate chronlists displayed here, one for Benjamin and one for Julia):

<img width="1011" alt="Screen Shot 2019-09-20 at 4 43 30 PM" src="https://user-images.githubusercontent.com/101482/65364304-d29c2700-dbc5-11e9-9563-0aad85c812d4.png">

---

### Chronlist elements mapping
Below is an annotated screenshot showing how the `<chronlist>` child elements are mapped to HTML. For reference, here's the [relevant page in the EAD 2002 spec](https://www.loc.gov/ead/tglib/elements/chronlist.html). Some details:

* The `<chronlist>` structure is mapped to an HTML table.
* If there is a `<head>` or `<listhead>` element within the chronlist, it is mapped to a `<caption>`.
* The table gets two `<th>` elements to set up table column headers of Date and Event (see example code for the table below).
* `<chronitem>` becomes a `<tr>` of the table.
* `<date>` is the first `<td>` of the table.
* I believe we can safely discard any `<eventgrp>` elements that are present.
* `<event>` is the second `<td>` of the table.
* If there are multiple `<event>` elements within an `<eventgrp>` (or in the same `<chronitem>`), add a `<br>` before each `<event>` after the first one (e.g., the "1769" item has two `<event>`s).

Here's a more visual representation of the mapping:

<img width="1011" alt="Screen Shot 2019-09-20 at 4 34 35 PM" src="https://user-images.githubusercontent.com/101482/65364618-e0eb4280-dbc7-11e9-9174-48b36a76e813.png">

### HTML example
Here's an abbreviated example of a[ source EAD's `<chronlist>`](https://github.com/sul-dlss/arclight-demo/blob/aecb5c6c505dc5385a4c313ad0bcaf292ce077a1/data/ead/duke-rubenstein/rushbenjaminandjulia-ead2002.xml#L124) mapped to the HTML I used for the screenshots above:

```html
<table class="chronlist">
  <caption class="chronlist-head">Benjamin Rush</caption>
  <thead>
    <tr>
      <th scope="col">Date</th>
      <th scope="col">Event</th>
    </tr>
  </thead>
  <tbody>
    <tr class="chronlist-item">
      <td class="chronlist-item-date">1746 January 4</td>
      <td class="chronlist-item-event">
        Born, in Byberry Township, Pa.
      </td>
    </tr>
    <tr class="chronlist-item">
      <td class="chronlist-item-date">1760</td>
      <td class="chronlist-item-event">
        Graduated with A. B., College of New Jersey (Princeton)
      </td>
    </tr>
    <tr class="chronlist-item">
      <td class="chronlist-item-date">1769</td>
      <td class="chronlist-item-event">
        Began medical practice in Philadelphia
        <br>
        Appointed Professor of Chemistry in College of Philadelphia's medical department
      </td>
    </tr>
    <tr class="chronlist-item">
      <td class="chronlist-item-date">1797-1813</td>
      <td class="chronlist-item-event">
        Treasurer of the U.S. Mint
      </td>
    </tr>
    <tr class="chronlist-item">
      <td class="chronlist-item-date">1813</td>
      <td class="chronlist-item-event">
        Died
      </td>
    </tr>
  </tbody>
</table>
```

### CSS example
Below is the CSS I used for styling the table. Feel free to adjust things if other approaches make more sense, as long as we end up with something that looks pretty close to my example above (e.g., substitute spacing and color variables for my hardcoded values).

```css
.chronlist td,
.chronlist th {
    border-bottom: 1px solid #dee2e6;
    padding: 0.25rem;
    vertical-align: top;
}

.chronlist {
    margin-bottom: 20px;
}

td.chronlist-item-date {
    font-weight: 500;    
    width: 15ch;
}

.chronlist th {
    font-weight: 500;
}

.chronlist + .chronlist-head {
    margin-top: 30px;
}

caption.chronlist-head {
    caption-side: top;
    color: #343a40;
}
```

**Comment by noahgh221** [comment]
@ggeisler , thanks for the thorough recommendation. This looks great!
