### ISSUE TITLE
digital_objects_ssm includes empty string for Large Components List EAD fixture

### ISSUE THREAD

**Issue by estelendur** [projectblacklight/arclight#771]
Not sure why it's indexing an empty string in addition to a real digital object, but it seems incorrect.

**Comment by seanaery** [comment]
Thanks for reporting this, @estelendur. Looks like the reason is that one of the two`<dao>` elements in this example is top-level, i.e., a child of the `<archdesc>` (which is valid EAD) and not in of any particular component of the collection. Our indexing rules don't currently account for this possibility, hence the error.
```
digital_objects_ssm: [
  "",
  "{"label":"1st Street Arcade San Francisco","href":"https://purl.stanford.edu/zr891kq4418"}"
],
```
![Screen Shot 2019-09-13 at 9 01 20 AM](https://user-images.githubusercontent.com/3933756/64865595-aa318d00-d607-11e9-8ebd-5ed901e2e058.png)

**Comment by seanaery** [comment]
On second thought, I spoke too soon -- this particular problem is unrelated to top-level `<dao>`s in the `<archdesc>`. I'll dig in a bit more.

**Comment by seanaery** [comment]
OK, the bug is: when a component's  `<dao>` isn't a child of its `<did>` it isn't getting indexed correctly. Rather than getting JSON for the object in `digital_objects_ssm`, we get only the text content of the `<dao>` node, which is sometimes blank, esp. if there's no `<daodesc>` text. 

Whether there's text or not the component view will throw this `JSON::ParserError` if there's a value in `digital_objects_ssm` that isn't JSON. In addition to fixing the indexing maybe we can make the view more resilient too.
