### ISSUE TITLE
Any top-level value for archdesc/@level other than "collection" throws an error in UI

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#776]
See for example umich-bhl-0728 and umich-bhl-851981

<img width="1097" alt="Screen Shot 2019-09-13 at 9 30 53 AM" src="https://user-images.githubusercontent.com/73732/64878828-44460500-d609-11e9-832b-574bd19d927d.png">

If I click through to the component, and then click through to the collection, the application throws an exception https://arclight-demo.projectblacklight.org/catalog/umich-bhl-851981

**Comment by seanaery** [comment]
@anarchivist The issue with these examples is that their top-level wrapper is `<archdesc level="recordgrp">` instead of `<archdesc level="collection">`. We'll need to build in more resiliency to display show pages for non-"collection" top-level documents without breaking.

In essence, without being `level="collection"`, it's falling back to the default show view, which is pulling in a `component_contents` partial, which is expecting the document to have a `component_level`, which it doesn't have because it isn't a component, etc., etc...

**Comment by seanaery** [comment]
@anarchivist A couple followup questions:

1) Is it a correct assumption that the desired display for all finding aids like this (where the top-level wrapping `archdesc level` is NOT `"collection"`) resembles our current display for a collection show page? 

2) Is it OK that the primary navigation (where one can browse either Repositories or Collections) will exclude browsing to finding aids like this? Note that the [Collections browse](https://arclight-demo.projectblacklight.org/collections) filters to `level="collection"` only.

**Comment by anarchivist** [comment]
@seanaery 

> 1) Is it a correct assumption that the desired display for all finding aids like this (where the top-level wrapping `archdesc level` is NOT `"collection"`) resembles our current display for a collection show page? 

At this point, yes. I can't imagine too many cases where we'd want something different.

> 2) Is it OK that the primary navigation (where one can browse either Repositories or Collections) will exclude browsing to finding aids like this? Note that the [Collections browse](https://arclight-demo.projectblacklight.org/collections) filters to `level="collection"` only

We probably need to change this (and change indexing) to specify a "top-level description" to get this filter. I can create a new ticket for this.

**Comment by seanaery** [comment]
@anarchivist I changed the title of this ticket to reflect the bug that needs to be addressed.
Here's a screenshot of the error in my local environment when visiting a show page for an EAD that has top-level `archdesc[@level='recordgrp']` instead of `collection` (in this case, `[umich-bhl-851981](https://raw.githubusercontent.com/sul-dlss/arclight-demo/master/data/ead/umich-bhl/umich-bhl-851981.xml)`).

![archdesc-level-error](https://user-images.githubusercontent.com/3933756/65049948-9d2cda80-d934-11e9-8b1e-b462ec30774a.png)
