### ISSUE TITLE
Component IDs are not getting set correctly when missing

### ISSUE THREAD

**Issue by cmkpowell** [projectblacklight/arclight#785]
Whether you browse the repositories page or search for known items (Douglas MacArthur, Tinder, 
 Hemingway) I'm not finding anything from cmu-clarke or umich-wlcl. 

The files are there in arclight-demo/data/ead.  These are non-ASpace, EAD 2002 DTD finding aids so may be outliers with new indexing issues.

**Comment by anarchivist** [comment]
Error logs from trying indexing both the Clarke and Clements fixtures locally: https://gist.github.com/anarchivist/a5c5edccd3a7be38e8a64cc185edf93d

**Comment by anarchivist** [comment]
It looks like both the Clements and Clarke fixtures are failing on [line 288](https://github.com/projectblacklight/arclight/blob/master/lib/arclight/traject/ead2_config.rb#L288) of the Traject config (within the definition for `parent_ssm`).

I'm wondering if this has to do with the fact that these are finding aids that don't have component IDs, and hence the the lookup of of the `id` attribute's value is failing.

**Comment by seanaery** [comment]
@anarchivist & @cmkpowell -- I've looked at this a bit and can confirm there's a minor bug in the ID-minting code introduced in #664. While the log reports that an ID was minted, that ID isn't actually getting written to the component. I'll plan to work on the following:

1. fix the bug so the ID gets written
2. add a sample test fixture to the arclight engine that lacks component IDs
3. revise existing tests around this feature

Note that at least the [hemingwayernest](https://github.com/sul-dlss/arclight-demo/blob/master/data/ead/cmu-clark/hemingwayernest.xml) finding aid is also affected by bug #776 since it has `archdesc[@level="recordgrp"]`.

**Comment by seanaery** [comment]
@anarchivist & @cmkpowell -- I retitled this ticket to reflect the root problem that needs to be addressed.

**Comment by anarchivist** [comment]
Thanks @seanaery!

**Comment by seanaery** [comment]
@anarchivist & @cmkpowell -- Heads-up: I've got a fix for this issue here #807. Part of that change was to create a new Arclight engine test fixture using CMU Clarke's [Hemingway EAD](https://github.com/sul-dlss/arclight-demo/blob/master/data/ead/cmu-clark/hemingwayernest.xml) converted to XSD and truncated a bit. If by any chance you'd rather we use a different example -- or an entirely fake hand-crafted fixture -- we can switch that out.

**Comment by anarchivist** [comment]
Excellent. Thanks @seanaery!

**Comment by cmkpowell** [comment]
I don't have any particular concerns, but it's not my finding aid! Is it good protocol for me to ask Marian?

**Comment by anarchivist** [comment]
@cmkpowell From a test-suite standpoint for ArcLight, I'm not sure it matters - but I'll note to get the CMU fixtures to work properly we still need to work on #776 and #778.
