### ISSUE TITLE
Responsive tweaks: Collapse labels for "Sort by relevance" and "10 per page" buttons

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#804]
Split out from #793

Comment from @jkeck:
>WRT dropping the labels of the sort and per page drop downs in a responsive manner, this will most likely require changes upstream in Blacklight. 

<img width="296" alt="Screen Shot 2019-09-11 at 4 45 35 PM" src="https://user-images.githubusercontent.com/101482/64987062-40221d80-d87d-11e9-86a1-f2e4138af739.png">

- [x] The label for the "Sort by relevance" button should be shortened to read "Sort"
- [x] The label for the "10 per page" button should be shortened to read "10" (or whatever the current selection is)

**Comment by mejackreed** [comment]
Should we try to just do this upstream in Blacklight?

**Comment by ggeisler** [comment]
For reference, here's the problem we need to solve (otherwise I wouldn't suggest reducing the labels):

<img width="386" alt="Screen Shot 2019-09-17 at 3 09 34 PM" src="https://user-images.githubusercontent.com/101482/65083458-78992880-d95d-11e9-86e6-5071e5925941.png">

That's using Chrome's "iPhone 6/7/8" view, which is what (I think) JV and I usually use as our narrowest viewport to worry about supporting. 

Reducing the labels should get those buttons all in one row, and we then use the other row for the "All results | Group by collection" button group. Otherwise we'd have three stacked rows of buttons...

**Comment by camillevilla** [comment]
![Blacklight demo](https://user-images.githubusercontent.com/5402927/65086755-d6327280-d967-11e9-8484-32862cd8ef2c.png)
Yeah, that's not a bad idea. I was worried this only made sense for ArcLight, but this screenshot of the blacklight demo site at 375px shows it would be a nice upstream thing as well.
