### ISSUE TITLE
Collection context tree: show sibling and parents above current component

### ISSUE THREAD

**Issue by camillevilla** [projectblacklight/arclight#812]
Split out of #670 / #673
Related to #811. 
   - One sibling _above_ the current component is displayed; any siblings above that are hidden, with an Expand button to mark the absence. (2)
   - The immediate parent _above_ the current component is shown; the remainder of the tree to the top is hidden, with an expand button. (3)

![](https://user-images.githubusercontent.com/6945691/63970094-29479280-ca58-11e9-96d0-adbffe79733b.png)

**Comment by jrgriffiniii** [comment]
I'm starting to work to restructure the underlying JavaScript functionality which should enable that the "Expand" buttons are offered for parent/parent-sibling nodes in https://github.com/projectblacklight/arclight/commit/877908f99d121ad9c937607f81d9294f21ba0522

I will likely seek out feedback before progressing too much further with this in order to ensure that these proposed changes are acceptable.  Please note that I am also working directly off of the approach which I proposed in https://github.com/projectblacklight/arclight/pull/889

**Comment by mejackreed** [comment]
Resolved previously in #913.
