### ISSUE TITLE
Remove masthead from search results if not faceted by Repository

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#861]
When you limit search results by **Repository**, you get the Repository masthead. 
https://arclight-demo.projectblacklight.org/?f%5Brepository_sim%5D%5B%5D=Stanford+University+Libraries.+Special+Collections+and+University+Archives&q=&search_field=all_fields

This is as intended. Yay!

When you limit search results by **Collection** (or anything else), you _might_ get... the Repository masthead. 
https://arclight-demo.projectblacklight.org/?f%5Bcollection_sim%5D%5B%5D=Philip+G.+Zimbardo+papers%2C+1953-2011&q=&search_field=all_fields

I can't tell why this is happening, but it is misleading/disorienting, and was not intended by the original designs. 

**Acceptance criteria**

- [ ] Display the Repository masthead _only_ for searches with a Repository facet explicitly selected.

**Comment by anarchivist** [comment]
I think this happens when a filtered search only matches results from a specific repository. In this case, the Zimbardo papers and all their components are associated with Stanford. Similarly, if you [filter by Creator and select "Rush, Benjamin"](https://arclight-demo.projectblacklight.org/?f%5Bcreator_ssim%5D%5B%5D=Rush%2C+Benjamin%2C%0A++++++++++++++++1746-1813&q=&search_field=all_fields) ... then you see the Duke Rubenstein Library repository card at the top of the results:

![bug](https://user-images.githubusercontent.com/73732/65348785-cfd60d80-db96-11e9-9efe-3b01d7b1b62c.gif)

**Comment by jvine** [comment]
Oh, that's even worse. The masthead really is meant to appear ONLY when faceted by repository. In other contexts, it's pushing something large into the prime area of the page that does not directly reflect what the user just requested, and deprecates what they DID request.

**Comment by anarchivist** [comment]
I just modified the ticket to specify that we should not display this unless the Repository facet is selected.
