### ISSUE TITLE
Arclight is incompatible with Rails 6.0

### ISSUE THREAD

**Issue by khanhvu98kk** [projectblacklight/arclight#954]
When running the install instructions on this [link](https://github.com/projectblacklight/arclight/wiki/Creating,-installing,-and-running-your-ArcLight-application), given in the README, there was a problem with installing the Arclight gem because the arclight.gemspec requires a Rails version of 5.

**Comment by dl-maura** [comment]
Just chiming to say this still appears to be an issue, although possibly due to a different problem (I see there was a merged rails-6 branch). This might be due to a change in blacklight or the devise gem, current behavior is things just hang at the generating user step:
`generate blacklight:user`
`rails generate blacklight:user user --devise true`

No errors are thrown (at least none display) it just will sit there forever and never complete setup/move on to the next step.

**Comment by jcoyne** [comment]
We no longer support Rails 6.0. Please try on 6.1 or 7.0
